import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const here = dirname(fileURLToPath(import.meta.url));

test("MCP stdio server advertises only local read-oriented tools", async (context) => {
  const dataDirectory = await mkdtemp(join(tmpdir(), "aisec-mcp-schema-"));
  context.after(() => rm(dataDirectory, { recursive: true, force: true }));
  const corruptedScanId = "scan_00000000-0000-4000-8000-000000000001";
  const target = join(dataDirectory, "target");
  await mkdir(join(dataDirectory, "scans"), { recursive: true });
  await mkdir(target);
  await writeFile(join(dataDirectory, "scans", `${corruptedScanId}.json`), JSON.stringify({ schemaVersion: "1.0.0", scanId: corruptedScanId }));
  await writeFile(join(target, "policy.yml"), "schemaVersion: 1.0.0\n");
  const cli = join(here, "..", "src", "cli.js");
  const child = spawn(process.execPath, [cli, "mcp"], { env: { ...process.env, AISEC_DATA_DIR: dataDirectory }, stdio: ["pipe", "pipe", "pipe"] });
  let output = "";
  child.stdout.setEncoding("utf8");
  child.stdout.on("data", (chunk: string) => { output += chunk; });
  const meta = { "io.modelcontextprotocol/protocolVersion": "2026-07-28", "io.modelcontextprotocol/clientCapabilities": {} };
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 1, method: "server/discover", params: { _meta: meta } })}\n`);
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 2, method: "tools/list", params: { _meta: meta } })}\n`);
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 3, method: "initialize", params: { protocolVersion: "2025-11-25", capabilities: {}, clientInfo: { name: "test", version: "1" } } })}\n`);
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 4, method: "tools/call", params: { _meta: meta, name: "get_report", arguments: { reference: "/etc/passwd" } } })}\n`);
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 5, method: "tools/call", params: { _meta: meta, name: "get_report", arguments: { reference: corruptedScanId } } })}\n`);
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: 6, method: "tools/call", params: { _meta: meta, name: "run_predeploy_scan", arguments: { path: target, policy: join(target, "policy.yml") } } })}\n`);
  child.stdin.end();
  await once(child, "close");
  const responses = output.trim().split("\n").map((line) => JSON.parse(line));
  assert.deepEqual(responses[0].result.supportedVersions, ["2026-07-28"]);
  assert.equal(responses[0].result._meta["io.modelcontextprotocol/serverInfo"].name, "aisec");
  assert.equal(responses[1].result.resultType, "complete");
  assert.equal(responses[1].result.cacheScope, "public");
  const names = responses[1].result.tools.map((tool: { name: string }) => tool.name);
  assert.deepEqual(names, ["inspect_project", "run_predeploy_scan", "get_report", "create_fix_contract", "verify_fix"]);
  const predeploy = responses[1].result.tools.find((tool: { name: string }) => tool.name === "run_predeploy_scan");
  const verifyFix = responses[1].result.tools.find((tool: { name: string }) => tool.name === "verify_fix");
  assert.equal(predeploy.inputSchema.properties.policy.type, "string");
  assert.equal(predeploy.inputSchema.properties.confirmPolicySuppressions.type, "boolean");
  assert.equal(verifyFix.inputSchema.properties.policy.type, "string");
  assert.equal(verifyFix.inputSchema.properties.confirmPolicySuppressions.type, "boolean");
  assert.ok(!names.includes("verify_web"));
  assert.ok(responses[1].result.tools.every((tool: { annotations: { readOnlyHint: boolean } }) => tool.annotations.readOnlyHint));
  assert.equal(responses[2].result.protocolVersion, "2025-11-25");
  assert.equal(responses[3].error.code, -32602);
  assert.match(responses[3].error.message, /not arbitrary file paths/);
  assert.equal(responses[4].error.code, -32602);
  assert.match(responses[4].error.message, /ScanReport does not match schema/);
  assert.equal(responses[5].error.code, -32602);
  assert.match(responses[5].error.message, /outside the scanned target/);
});
